### ISSUE TITLE
toBytes should consider Codec.Encode

### ISSUE THREAD

**Issue by bep** [asdine/storm#10]
It may be confusing to some (including me) that the keys are encoded with some ... other encoder (gob). Esp. if you want to interact directly with the BoltDB. 

This would potentially be a breaking change, though.

**Comment by asdine** [comment]
The reason behind this implementation of `toBytes` is that it was faster in some cases to test [this](https://github.com/asdine/storm/blob/master/helpers.go#L15-L24) before calling `gob` and also because `json.Marshal` doesn't handle every types. You can test that by changing the content of the function by `return json.Marshal(key)` and running the tests.

If we use the Codec we are not sure that it will actually work with some types that normally do.

Paradoxically, i believe the current implementation of `toBytes` allows to encode the keys in a predictable way and allows to use a `Stringer` a `json.Marshaller`, etc. 
But i can be wrong, i am open to suggestions

**Comment by asdine** [comment]
I was thinking that we can use an option. I get your point, it is useful for those who wants to interact with Bolt directly, but to avoid breaking the database we can make it optional.
