### ISSUE TITLE
 `storm:"index" storm:"unique"` is ignoring the unique constraint

### ISSUE THREAD

**Issue by conoro** [asdine/storm#33]
If I have a struct field defined as:

SubURL    string `storm:"unique"`

Then I can safely try to create the same entry in the DB multiple times, knowing that only the first one will success.

But if I define it as:

SubURL          string `storm:"index" storm:"unique"`

Then "unique" is ignored and I get duplicate entries in the DB for the same contents.

Ah, just as I was writing this I tried 

SubURL    string `storm:"unique" storm:"index"`

And that worked. So the order of the tags seems to be important. Is this a feature or a bug?

**Comment by asdine** [comment]
You are not supposed to use the same tag multiple times in go i believe, one of them will get ignored.
So in general you would do something like this:

```go
`json:"blabla,omitempty"`
```

instead of 
```go
`json:"blabla" json:"omitempty"`
```

As of Storm, only one value for the storm tag is currently supported so it is either `storm:"unique"` or `storm:"index"`.

The difference between `unique` and `index` is only that the latter allows multiple ids for the same value. `unique` IS an `index` but has an additional unicity constraint, so you don't need to write both.

**Comment by conoro** [comment]
Ah got it, thanks!
