### ISSUE TITLE
AutoIncrement fails with embedded struct

### ISSUE THREAD

**Issue by bep** [asdine/storm#38]
This fails with an error:

```go
type Base struct {
		ID int `storm:"id"`
	}

	type User struct {
		Base      `storm:"inline"`
		Group     string `storm:"index"`
		Email     string `storm:"unique"`
		Name      string
		Age       int
		CreatedAt time.Time `storm:"index"`
	}

	dir, _ := ioutil.TempDir(os.TempDir(), "storm")
	defer os.RemoveAll(dir)

	// Open takes a list of optional options as last argument.
	// AutoIncrement enables auto-incrementing ids.
	db, err := storm.Open(filepath.Join(dir, "storm.db"), storm.AutoIncrement())

	fmt.Println(err)
	// Output: <nil>

	user := User{
		Group:     "staff",
		Email:     "john@provider.com",
		Name:      "John",
		Age:       21,
		CreatedAt: time.Now(),
	}

	err = db.Save(&user)

	fmt.Println(err)
	// Output: <nil>

	fmt.Println(user.ID)
	// Output: 1
```

**Comment by asdine** [comment]
A pointer to the id field is stored in the [`identInfo` struct](https://github.com/asdine/storm/blob/master/extract.go#L136) as a `*structs.Field`. The problem is that when this field is from an embedded struct it is not settable (i don't know why).
Maybe i should store a pointer to the raw value, instead of storing the `*structs.Field` in `identInfo` and manually set the auto-incremented value [here](https://github.com/asdine/storm/blob/master/save.go#L63).

I don't know if it will work, i will try as soon as i can

**Comment by asdine** [comment]
The bug was related to a bug in [structs](https://github.com/fatih/structs/issues/56). Using reflection directly solves the issue
