### ISSUE TITLE
Index types should be moved to its own package

### ISSUE THREAD

**Issue by bep** [asdine/storm#39]
I had a look at the generated GoDoc, and it doesn't look bad, but the Index types clutters the API (Index, ListIndex, UniqueIndex).

I may be missing something, but shouldn't these be undexported? Are they of real value outside of the storm package?

**Comment by asdine** [comment]
The idea was to be able to create indexes at will. I thought it would be useful when dealing with dynamic objects (maps coming from JSON payload for example), that can't have a prepared structure.
Here is an example:

```go
data := map[string]interface{}{
	"id":    "an id",
	"email": "john@provider.com",
}

db.Bolt.Update(func(tx *bolt.Tx) error {
	dbx := db.WithTransaction(tx)

	b, err := dbx.CreateBucketIfNotExists(tx, "myBucket")
	assert.NoError(t, err)
        
    // we create an index for email
	idx, err := NewUniqueIndex(b, []byte("email"))
	assert.NoError(t, err)

	email := []byte(data["email"].(string))
	id := []byte(data["id"].(string))

	err = idx.Add(email, id)
	assert.NoError(t, err)

	raw, err := gob.Codec.Encode(data)
	assert.NoError(t, err)

	err = b.Put(id, raw)
	assert.NoError(t, err)

	assert.Equal(t, id, idx.Get(email))
	assert.Equal(t, raw, b.Get(idx.Get(email)))
	return nil
})
```

A use case would be the possibility to dynamically create models of data and to select which fields are to be indexed.

The problem is that i am probably the only one using that because it is too heavy to use, the API is not intuitive.

I think i should find a better way to deal with dynamic objects that would be officially part of the API and keep the indexes unexported.

Any idea or advice is welcome

**Comment by bep** [comment]
>A use case would be the possibility to dynamically create models of data and to select which fields are to be indexed.

That makes sense ... How about moving the Index stuff below /index ...? I have not looked closely if that is possible, but that would get rid of the distraction for people looking at the "core" functions.

**Comment by asdine** [comment]
I totally agree, the documentation must be as clear as possible (at least for the core functions)

**Comment by bep** [comment]
That cleaned up very nicely. A small round improving the GoDoc (esp. adding missing package docs) would put this library in my "clean code" department.

**Comment by asdine** [comment]
Yep that's planned :+1:
